# ServiceAccount with Docker registry credentials for Knative
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-docker-sa
  namespace: default
imagePullSecrets:
- name: docker-registry-secret

---
# ServiceAccount for test-realtime-working namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-docker-sa
  namespace: test-realtime-working
imagePullSecrets:
- name: docker-registry-secret