# Loft Platform Values
# Minimal configuration for sleep mode management

# Enable the platform features we need
platform:
  enabled: true

# Configure sleep mode controller
sleepMode:
  enabled: true

# Admin configuration
admin:
  # Set admin user
  username: admin
  # Create a default password (change this!)
  password: "admin123"

# Resource limits (adjust based on your cluster size)
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 200m
    memory: 256Mi

# Enable RBAC
rbac:
  create: true

# Service configuration
service:
  type: LoadBalancer
  # Use port 80 for easier access
  port: 80
  targetPort: 8080

# Standard sleep mode configuration
sleepMode:
  enabled: true
  
# Security settings
security:
  # Use Loft's built-in authentication
  oidc:
    enabled: false
  
# Disable features we don't need
harbor:
  enabled: false

ingress:
  enabled: false