apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: default
  annotations:
    # Prevent ArgoCD from managing this secret
    argocd.argoproj.io/compare: "false"
    argocd.argoproj.io/sync: "false"
  labels:
    managed-by: manual
type: Opaque
stringData:
  token: "${PERSONAL_ACCESS_TOKEN}"
  user: "shlapolosa"
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-credentials
  namespace: default
  annotations:
    # Prevent ArgoCD from managing this secret
    argocd.argoproj.io/compare: "false"
    argocd.argoproj.io/sync: "false"
  labels:
    managed-by: manual
type: Opaque
stringData:
  signing-secret: "${SLACK_SIGNING_SECRET}"