apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: default
  annotations:
    # Prevent ArgoCD from managing this secret
    argocd.argoproj.io/compare: "false"
    argocd.argoproj.io/sync: "false"
  labels:
    managed-by: manual
type: Opaque
stringData:
  token: "${PERSONAL_ACCESS_TOKEN}"
  personal-access-token: "${PERSONAL_ACCESS_TOKEN}"
  user: "${GITHUB_USERNAME}"
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: default
  annotations:
    # Prevent ArgoCD from managing this secret
    argocd.argoproj.io/compare: "false"
    argocd.argoproj.io/sync: "false"
  labels:
    managed-by: manual
type: Opaque
stringData:
  registry: "docker.io"
  username: "${DOCKER_USERNAME}"
  password: "${DOCKER_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: slack-credentials
  namespace: default
  annotations:
    # Prevent ArgoCD from managing this secret
    argocd.argoproj.io/compare: "false"
    argocd.argoproj.io/sync: "false"
  labels:
    managed-by: manual
type: Opaque
stringData:
  signing-secret: "${SLACK_SIGNING_SECRET}"