# Manual secrets template - populated from .env file via setup-secrets.sh
# Variables are substituted using envsubst

---
apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: default
  labels:
    managed-by: manual
  annotations:
    argocd.argoproj.io/compare: "false"
    argocd.argoproj.io/sync: "false"
type: Opaque
stringData:
  token: "${PERSONAL_ACCESS_TOKEN}"
  personal-access-token: "${PERSONAL_ACCESS_TOKEN}"
  user: "${GITHUB_USERNAME}"

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: default
  labels:
    managed-by: manual
  annotations:
    argocd.argoproj.io/compare: "false"
    argocd.argoproj.io/sync: "false"
type: Opaque
stringData:
  registry: "docker.io"
  username: "${DOCKER_USERNAME}"
  password: "${DOCKER_PASSWORD}"

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: default
  labels:
    managed-by: manual
  annotations:
    argocd.argoproj.io/compare: "false"
    argocd.argoproj.io/sync: "false"
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "docker.io": {
          "username": "${DOCKER_USERNAME}",
          "password": "${DOCKER_PASSWORD}",
          "auth": "${DOCKER_AUTH}"
        }
      }
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: slack-credentials
  namespace: default
  labels:
    managed-by: manual
  annotations:
    argocd.argoproj.io/compare: "false"
    argocd.argoproj.io/sync: "false"
type: Opaque
stringData:
  signing-secret: "${SLACK_SIGNING_SECRET}"