apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-gateway-config
  namespace: default
  labels:
    app.kubernetes.io/component: graphql-gateway
    app.kubernetes.io/name: api-gateway
data:
  config.yaml: |
    # GraphQL Gateway Configuration
    gateway:
      name: "api-gateway"
      autoDiscovery: true
      refreshInterval: "5m"
    serviceDiscovery:
      selector:
        app.kubernetes.io/managed-by: kubevela
      namespaces: ["default"]
    cors:
      enabled: true
      origin: "*"
    playground:
      enabled: true