apiVersion: v1
kind: ConfigMap
metadata:
  name: test-gateway-config
  namespace: default
data:
  gateway.yaml: |
    server:
      port: 8080
      host: "0.0.0.0"
      cors:
        enabled: true
        origin: "*"
        methods: ["GET", "POST", "OPTIONS"]
        headers: ["Content-Type", "Authorization", "X-API-Key"]
    
    discovery:
      namespace: "default"
      labelSelector: "app.kubernetes.io/managed-by=kubevela"
      interval: "30s"
      autoDiscovery: true
      retryDelay: "10s"
      maxRetries: 3
      federationAnnotation: "graphql.federation/enabled"
    
    graphql:
      playground: true
      introspection: true
      endpoint: "/graphql"
      
    security:
      rateLimit:
        windowMs: 900000
        max: 1000
      helmet:
        enabled: true
        
    logging:
      level: "debug"
      format: "json"