apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-simple-workflow
  namespace: default
  labels:
    test-type: "simple-workflow"
    created-by: "claude-code"
  annotations:
    description: "Simple test to verify workflow execution and repository creation"
    test-purpose: "Verify user-service workflow completes and creates microservice"
spec:
  components:
  # Single WebService to test workflow completion
  - name: user-service-test
    type: webservice
    properties:
      image: socrates12345/user-service-test:latest
      port: 8080
      language: python           
      framework: fastapi
      repository: test-healthcare-platform
---
# SUCCESS CRITERIA:
# 1. ✅ Workflow trigger job completes successfully 
# 2. ✅ ApplicationClaim created for user-service-test
# 3. ✅ Microservice added to test-healthcare-platform repository
# 4. ✅ GitHub Actions workflow created (comprehensive-gitops.yml)
# 5. ✅ Knative service user-service-test created with correct image
# 6. ✅ Chat-repo-creator job runs and skips (not RASA service)
#
# VERIFICATION COMMANDS:
# kubectl get ksvc user-service-test
# kubectl get applicationclaim user-service-test  
# kubectl get jobs | grep user-service-test
# kubectl logs job/user-service-test-workflow-trigger
# kubectl logs job/user-service-test-chat-repo-creator