apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: final-federation-test
  namespace: default
spec:
  components:
  - name: final-gateway
    type: graphql-gateway
    properties:
      language: "nodejs"
      framework: "graphql-gateway"
      repository: "final-federation-gateway"
      configMapName: "final-federation-platform-config"
      env:
      - name: POLLING_INTERVAL
        value: "10000"
      - name: LOG_LEVEL
        value: "debug"
      - name: SERVICE_SELECTOR_LABELS
        value: "graphql.federation/enabled=true"
      - name: FEDERATION_ANNOTATION
        value: "graphql.federation/enabled"
      - name: NAMESPACE
        value: "default"
  - name: final-service
    type: webservice
    properties:
      image: socrates12345/business-analyst-anthropic:1.1.fdfb37a
      ports:
      - port: 8080
        expose: false
      enableGraphQLFederation: true
  - name: final-infra
    type: graphql-platform
    properties:
      name: "final-federation-platform"
      serviceSelector:
        "graphql.federation/enabled": "true"
      autoSchema: true
      schemaRefreshInterval: "2m"
      exposeIntrospection: false