---
# Simple GraphQL Gateway Test with One Service
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: simple-graphql-test
  namespace: default
spec:
  components:
  # 1. Simple webservice that exposes a REST API
  - name: hello-service
    type: webservice
    properties:
      # Using httpbin as a test service that has OpenAPI spec
      image: kennethreitz/httpbin:latest
      port: 80
      environment:
        SERVICE_NAME: "hello-service"
      # Mark for GraphQL exposure
      annotations:
        "graphql.oam.dev/exposed": "true"
        "graphql.oam.dev/path-prefix": "/api"
      
  # 2. GraphQL Gateway that will discover the service above
  - name: simple-gateway
    type: graphql-gateway
    properties:
      # Service discovery - find services with these labels
      serviceSelector:
        "app.kubernetes.io/name": "hello-service"
        "graphql.oam.dev/exposed": "true"
      
      # Enable auto schema generation
      autoSchema: true
      schemaRefreshInterval: "1m"  # Refresh every minute for testing
      
      # Enable introspection for development
      exposeIntrospection: true
      enableConsole: true
      
      # Simple admin secret for testing
      adminSecret: "test-secret-123"
      
      # Minimal resources
      resources:
        cpu: "250m"
        memory: "256Mi"