# Test Evolution: Real-time Platform Test
# Step 9: Start with realtime-platform component
# Expected: Real-time platform infrastructure creation and setup

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: streaming-platform-2025
  namespace: default
  annotations:
    test.oam.dev/step: "realtime-platform-validation"
    test.oam.dev/description: "Verify complete real-time streaming platform creation"
    test.oam.dev/expected: "Kafka, MQTT, Lenses HQ/Agent, Metabase, PostgreSQL infrastructure"
spec:
  components:
  # Real-time Platform Infrastructure - Critical Path Component
  - name: streaming-platform-2025
    type: realtime-platform
    properties:
      name: streaming-platform-2025
      image: streaming-platform:latest
      language: python
      framework: fastapi
      database: postgres
      visualization: metabase
      iot: true
      resources:
        cpu: "500m"
        memory: "1Gi"