# Test Evolution: Final Test with Fixed GitHub Username
# Step 8: Clean test with fully updated configuration
# Expected: Job created → HTTP call to Argo → Workflow with correct GitHub org → AppContainer + ApplicationClaim created → GitHub repos setup

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: invoice-system-test
  namespace: default
  annotations:
    test.oam.dev/step: "8"
    test.oam.dev/description: "Final test with fully corrected GitHub username configuration and applied manifests"
spec:
  components:
  # Simple webservice (existing image for baseline)
  - name: invoice-frontend
    type: webservice
    properties:
      name: invoice-frontend
      image: nginx:alpine
      port: 80
      healthPath: "/"
      environment:
        SERVICE_NAME: "invoice-frontend"
        ENV: "test"
  
  # NEW MICROSERVICE: Invoice processing service with Argo Workflow bootstrap
  - name: invoice-processor-service
    type: webservice
    properties:
      name: invoice-processor-service
      image: docker.io/socrates12345/invoice-processor-service:latest    # Non-existent image triggers bootstrap
      language: python                           # Triggers Argo Workflow
      framework: fastapi
      repository: invoice-platform-repo         # NEW REPOSITORY NAME
      source: "oam-driven"                       # Proper source detection
      port: 8080
      healthPath: "/health"
      environment:
        SERVICE_NAME: "invoice-processor-service"
        ENV: "test"
        MICROSERVICE_TYPE: "invoice-processor"