# Test Evolution: Real-time Platform Test
# Step 9: Start with realtime-platform component
# Expected: Real-time platform infrastructure creation and setup

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-realtime
  namespace: default
  annotations:
    test.oam.dev/step: "9"
    test.oam.dev/description: "Real-time platform infrastructure test"
spec:
  components:
  # Real-time Platform Infrastructure
  - name: test-realtime
    type: realtime-platform
    properties:
      name: test-realtime
      image: test-realtime:latest
      database: postgres
      visualization: metabase
      iot: true
      resources:
        cpu: "500m"
        memory: "1Gi"