apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-rasa-chatbot
  namespace: default
  labels:
    test-type: "rasa-focused"
    created-by: "claude-code"
  annotations:
    description: "Focused test for RASA chatbot component behavior"
    test-purpose: "Verify RASA chatbot workflow, ApplicationClaim creation, and chat-repo-creator logic"
spec:
  components:
  # RASA Chatbot Component Only
  - name: support-chat
    type: rasa-chatbot
    properties:
      rasaImage: "socrates12345/support-chat-rasa:latest"
      actionsImage: "socrates12345/support-chat-actions:latest"
      enableIstioGateway: true
      language: rasa            
      framework: chatbot
      repository: rasa-test-platform
---
# EXPECTED BEHAVIOR FOR RASA CHATBOT:
# 
# 1. ✅ Workflow trigger job should submit to Argo successfully
# 2. ✅ Argo workflow should create ApplicationClaim (if RASA creates claims)
# 3. ✅ Two Knative services created: support-chat-rasa and support-chat-actions
# 4. ✅ Chat-repo-creator should process (IS a RASA service)
# 5. ✅ Microservice structure created in repository
# 6. ✅ GitOps manifests created
# 7. ✅ Chat-specific GitHub Actions workflow (chat-gitops.yml)
#
# VERIFICATION COMMANDS:
# kubectl get ksvc | grep support-chat
# kubectl get applicationclaim support-chat
# kubectl get jobs | grep support-chat
# kubectl logs job/support-chat-workflow-trigger
# kubectl logs job/support-chat-chat-repo-creator
# kubectl logs job/support-chat-microservice-creator
# kubectl get workflows -n argo | grep support-chat