apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-webhook-app
  namespace: default
  labels:
    app-container: "health-service-platform"
spec:
  components:
    - name: user-service
      type: webservice
      properties:
        image: nginx:latest
        cpu: "100m"
        memory: "128Mi"
        language: "python"
        framework: "fastapi"
        database: "postgresql"
        cache: "redis"
    - name: order-service  
      type: webservice
      properties:
        image: nginx:latest
        cpu: "100m"
        memory: "128Mi"
        language: "java"
        framework: "springboot"
        database: "none"
        cache: "none"
  policies:
    - name: topology-policy
      type: topology
      properties:
        clusters: ["local"]