apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: simple-test
  namespace: default
spec:
  components:
  - name: simple-service
    type: webservice
    properties:
      image: nginx:alpine
      port: 80
      version: "latest"