# Minimal vcluster configuration that works with latest chart version
sync:
  toHost:
    pods:
      enabled: true
      enforceTolerations:
        - vclusterID=architecture-vizualisation:NoSchedule
    persistentVolumes:
      enabled: true
    persistentVolumeClaims:
      enabled: true
    storageClasses:
      enabled: true
    ingresses:
      enabled: true

# Enable CoreDNS (not embedded - that's pro only)
controlPlane:
  coredns:
    enabled: true
    embedded: false

# Service CIDR
serviceCIDR: "10.96.0.0/12"
