apiVersion: v1
kind: Secret
metadata:
  name: health-service-idp-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/shlapolosa/health-service-idp
  password: YOUR_GITHUB_TOKEN_HERE
  username: shlapolosa
---
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/shlapolosa/health-service-idp.git
  password: YOUR_GITHUB_TOKEN_HERE
  username: shlapolosa