version: '3.8'

services:
  business-analyst-deterministic:
    build: .
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped