---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: placeholder-realtime
  labels:
    app.kubernetes.io/name: mqtt
    app.kubernetes.io/component: broker
data:
  mosquitto.conf: |
    # Mosquitto Configuration for Health Data Pipeline
    allow_anonymous false
    password_file /mosquitto/config/passwd
    
    # MQTT Protocol
    listener 1883
    protocol mqtt
    
    # WebSockets Protocol  
    listener 9001
    protocol websockets
    
    # Persistence
    persistence true
    persistence_location /mosquitto/data/
    
    # Logging
    log_dest file /mosquitto/log/mosquitto.log
    log_type error
    log_type warning
    log_type notice
    log_type information
    
    # Connection settings
    max_keepalive 300
    max_connections 1000
  
  passwd: |
    # user1:password (hashed)
    user1:$7$101$Qm3aFsdhFxI7WmMr$Xk1qRpY+rz9oHZ8mK7qL2vN5tJ3wE6rS4dF8gH9jK2lM3nP5qR7sT9uV1wX3yZ5aB7cD9eF1gH3jK5lM7nP9qR
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data
  namespace: placeholder-realtime
  labels:
    app.kubernetes.io/name: mqtt
    app.kubernetes.io/component: broker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  namespace: placeholder-realtime
  labels:
    app.kubernetes.io/name: mqtt
    app.kubernetes.io/component: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mqtt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mqtt
        app.kubernetes.io/component: broker
    spec:
      containers:
      - name: mqtt
        image: eclipse-mosquitto
        ports:
        - containerPort: 1883
          name: mqtt
        - containerPort: 9001
          name: websockets
        volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config
        - name: mosquitto-data
          mountPath: /mosquitto/data
        - name: mosquitto-log
          mountPath: /mosquitto/log
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
      - name: mosquitto-data
        persistentVolumeClaim:
          claimName: mosquitto-data
      - name: mosquitto-log
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: placeholder-realtime
  labels:
    app.kubernetes.io/name: mqtt
    app.kubernetes.io/component: broker
spec:
  selector:
    app.kubernetes.io/name: mqtt
  ports:
  - port: 1883
    targetPort: 1883
    name: mqtt
  - port: 9001
    targetPort: 9001
    name: websockets