apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"name":"clustergateways.core.oam.dev"},"spec":{"group":"core.oam.dev","names":{"kind":"ClusterGateway","listKind":"ClusterGatewayList","plural":"clustergateways","singular":"clustergateway"},"scope":"Namespaced","versions":[{"name":"v1alpha1","schema":{"openAPIV3Schema":{"properties":{"spec":{"properties":{"access":{"properties":{"credential":{"properties":{"serviceAccountToken":{"description":"Name of the secret containing the token","type":"string"},"type":{"enum":["ServiceAccountToken","X509Certificate"],"type":"string"}},"type":"object"},"insecure":{"description":"Skip TLS verification","type":"boolean"}},"type":"object"},"clusterType":{"description":"Type of cluster (e.g., vcluster, eks, gke)","type":"string"},"endpoint":{"description":"API endpoint of the target cluster","type":"string"}},"type":"object"},"status":{"properties":{"conditions":{"items":{"properties":{"lastTransitionTime":{"type":"string"},"message":{"type":"string"},"reason":{"type":"string"},"status":{"type":"string"},"type":{"type":"string"}},"type":"object"},"type":"array"}},"type":"object"}},"type":"object"}},"served":true,"storage":true}]}}
  creationTimestamp: "2025-08-06T10:40:58Z"
  generation: 1
  name: clustergateways.core.oam.dev
  resourceVersion: "24448286"
  uid: 65d7684f-39ec-4e3f-b306-62d82b8bb7b0
spec:
  conversion:
    strategy: None
  group: core.oam.dev
  names:
    kind: ClusterGateway
    listKind: ClusterGatewayList
    plural: clustergateways
    singular: clustergateway
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              access:
                properties:
                  credential:
                    properties:
                      serviceAccountToken:
                        description: Name of the secret containing the token
                        type: string
                      type:
                        enum:
                        - ServiceAccountToken
                        - X509Certificate
                        type: string
                    type: object
                  insecure:
                    description: Skip TLS verification
                    type: boolean
                type: object
              clusterType:
                description: Type of cluster (e.g., vcluster, eks, gke)
                type: string
              endpoint:
                description: API endpoint of the target cluster
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ClusterGateway
    listKind: ClusterGatewayList
    plural: clustergateways
    singular: clustergateway
  conditions:
  - lastTransitionTime: "2025-08-06T10:40:58Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2025-08-06T10:40:58Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1alpha1
