apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualclusters.cluster.core.oam.dev
spec:
  conversion:
    strategy: None
  group: cluster.core.oam.dev
  names:
    kind: VirtualCluster
    listKind: VirtualClusterList
    plural: virtualclusters
    singular: virtualcluster
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              access:
                properties:
                  credential:
                    properties:
                      secretRef:
                        properties:
                          name:
                            description: Name of the secret containing credentials
                            type: string
                          namespace:
                            description: Namespace of the secret
                            type: string
                        type: object
                      type:
                        enum:
                        - ServiceAccountToken
                        - X509Certificate
                        type: string
                    type: object
                  endpoint:
                    description: Cluster API endpoint
                    type: string
                  insecure:
                    default: false
                    type: boolean
                type: object
              clusterType:
                description: Type of cluster (vcluster, eks, etc)
                type: string
            type: object
          status:
            properties:
              healthy:
                type: boolean
              message:
                type: string
            type: object
        type: object
    served: true
    storage: true