---
# Demo API Service for GraphQL Federation Testing
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: demo-api-service
  namespace: default
  labels:
    app.kubernetes.io/name: demo-api-service
    app.kubernetes.io/component: demo-service
    app.kubernetes.io/part-of: graphql-federation-test
    app.kubernetes.io/managed-by: kubevela
spec:
  components:
  - name: demo-rest-api
    type: webservice
    properties:
      # httpbin provides OpenAPI spec at /spec.json
      image: kennethreitz/httpbin:latest
      ports:
      - port: 80
        expose: true
      env:
      - name: PORT
        value: "80"
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:  
          memory: "128Mi"
          cpu: "100m"