---
# Direct Knative Service for GraphQL Federation Testing
# Bypassing the broken OAM webservice ComponentDefinition
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: simple-api-service
  namespace: default
  labels:
    app.kubernetes.io/name: simple-api-service
    app.kubernetes.io/component: rest-api
    app.kubernetes.io/managed-by: kubevela  # Required for GraphQL gateway discovery
    app.kubernetes.io/part-of: graphql-federation-test
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-api-service
        app.kubernetes.io/managed-by: kubevela
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
      - image: kennethreitz/httpbin:latest
        ports:
        - containerPort: 80
          name: http1
        env:
        - name: PORT
          value: "80"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /get
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /get  
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10