---
apiVersion: v1
kind: Secret
metadata:
  name: github-provider-secret
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "token": "${PERSONAL_ACCESS_TOKEN}",
      "owner": "shlapolosa"
    }

---
apiVersion: github.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: github-provider-secret
      namespace: crossplane-system
      key: credentials