---
# InfrastructureClaim XRD
# Defines the schema for internal infrastructure provisioning
# Pattern 3B: Infrastructure Components (Internal Services)
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xinfrastructureclaims.platform.io
spec:
  group: platform.io
  names:
    kind: XInfrastructureClaim
    plural: xinfrastructureclaims
  claimNames:
    kind: InfrastructureClaim
    plural: infrastructureclaims
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              infrastructureType:
                type: string
                enum:
                  - postgresql
                  - mongodb
                  - redis
                  - kafka
                  - clickhouse
                description: "Type of infrastructure to provision"
              size:
                type: string
                enum:
                  - small
                  - medium
                  - large
                default: small
                description: "Size of the infrastructure (affects CPU, memory, storage)"
              version:
                type: string
                description: "Version of the infrastructure component"
              replicas:
                type: integer
                minimum: 1
                maximum: 10
                default: 1
                description: "Number of replicas"
              namespace:
                type: string
                default: default
                description: "Namespace to deploy infrastructure"
              vcluster:
                type: string
                default: ""
                description: "Target vCluster for deployment (empty for host cluster)"
              highAvailability:
                type: boolean
                default: false
                description: "Enable high availability mode"
              backupEnabled:
                type: boolean
                default: false
                description: "Enable automated backups"
              monitoringEnabled:
                type: boolean
                default: true
                description: "Enable Prometheus monitoring"
              resources:
                type: object
                properties:
                  cpu:
                    type: string
                    description: "CPU request (e.g., 500m, 1)"
                  memory:
                    type: string
                    description: "Memory request (e.g., 1Gi, 2Gi)"
                  storage:
                    type: string
                    description: "Storage size (e.g., 10Gi, 50Gi)"
                description: "Resource specifications (overrides size defaults)"
              connectionSecretRef:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                description: "Secret to create with connection details"
                required:
                  - name
            required:
              - infrastructureType
              - connectionSecretRef
          status:
            type: object
            properties:
              ready:
                type: boolean
                description: "Whether the infrastructure is ready"
              endpoint:
                type: string
                description: "Service endpoint for the infrastructure"
              connectionSecret:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                description: "Reference to the connection secret created"