apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-kubernetes-provider-extended
rules:
# Allow full access to core Kubernetes resources
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
# Allow full access to all API groups for Kubernetes provider
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-kubernetes-provider-extended
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-kubernetes-provider-extended
subjects:
- kind: ServiceAccount
  name: provider-kubernetes-63506a3443e0
  namespace: crossplane-system