---
# Test Web Service for GraphQL Federation Testing
# This creates a simple REST service with OpenAPI spec that the GraphQL gateway can discover
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: test-api-service
  namespace: default
  labels:
    app.kubernetes.io/name: test-api-service
    app.kubernetes.io/component: test-service
    app.kubernetes.io/part-of: graphql-federation-test
    app.kubernetes.io/managed-by: kubevela
spec:
  components:
  - name: test-rest-api
    type: webservice
    properties:
      # Use httpbin which provides OpenAPI spec at /spec.json
      image: kennethreitz/httpbin:latest
      ports:
      - port: 80
        expose: true
      env:
      - name: PORT
        value: "80"
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
    traits:
    - type: ingress
      properties:
        domain: test-api-service.default.af433f091b55640038c23af3a641d716-112208284.us-west-2.elb.amazonaws.com
        http:
          "/": 80
---
# Alternative: Simple FastAPI service with built-in OpenAPI
apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: simple-fastapi-service
  namespace: default
  labels:
    app.kubernetes.io/name: simple-fastapi-service
    app.kubernetes.io/component: test-service
    app.kubernetes.io/part-of: graphql-federation-test
    app.kubernetes.io/managed-by: kubevela
spec:
  components:
  - name: fastapi-demo
    type: webservice
    properties:
      # Use tiangolo/uvicorn-gunicorn-fastapi which has OpenAPI at /openapi.json
      image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
      ports:
      - port: 80
        expose: true
      env:
      - name: MODULE_NAME
        value: "main"
      - name: VARIABLE_NAME
        value: "app"
      - name: PORT
        value: "80"
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "250m"
    traits:
    - type: ingress
      properties:
        domain: simple-fastapi-service.default.af433f091b55640038c23af3a641d716-112208284.us-west-2.elb.amazonaws.com
        http:
          "/": 80