apiVersion: v1
kind: Secret
metadata:
  name: github-analyzer-credentials
  namespace: crossplane-system
  annotations:
    description: "GitHub credentials for OAM Application Analyzer"
    note: "Token will be populated by host_cluster_lifecycle.sh script"
type: Opaque
data:
  # Token will be populated from PERSONAL_ACCESS_TOKEN by deployment script
  # This is a placeholder - real token injected at deployment time
  token: "cGxhY2Vob2xkZXI="  # placeholder (base64: "placeholder")