# Identity Service ComponentDefinition - Simplified
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: identity-service
  annotations:
    definition.oam.dev/description: "Domain-specific identity service generator"
spec:
  workload:
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Workflow
  schematic:
    cue:
      template: |
        output: {
          apiVersion: "argoproj.io/v1alpha1"
          kind: "Workflow"
          metadata: {
            generateName: context.name + "-identity-gen-"
            namespace: context.namespace
            labels: {
              "app.kubernetes.io/name": context.name
              "app.kubernetes.io/component": "identity-service"
            }
          }
          spec: {
            serviceAccountName: "argo-workflows-client"
            workflowTemplateRef: {
              name: "identity-service-generator"
            }
            arguments: {
              parameters: [
                {name: "domain", value: parameter.domain},
                {name: "repo-name", value: context.name + "-identity-service"},
                {name: "app-name", value: context.name},
                {name: "github-owner", value: "shlapolosa"}
              ]
            }
          }
        }
        
        parameter: {
          domain: "healthcare" | "financial" | "education"
        }