---
# Real-time Platform ComponentDefinition
# Architecturally identical to webservice pattern: OAM Component → Knative Service + Infrastructure Claims
apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: realtime-platform
  annotations:
    definition.oam.dev/description: "Complete real-time streaming platform with IoT, analytics, and stream processing"
spec:
  workload:
    definition:
      apiVersion: serving.knative.dev/v1
      kind: Service
    type: services.serving.knative.dev
  schematic:
    cue:
      template: |
        // Primary Output: Knative Service (OAM-compliant workload)
        output: {
          apiVersion: "serving.knative.dev/v1"
          kind: "Service"
          metadata: {
            name: context.name + "-realtime-service"
            namespace: context.namespace
            labels: {
              "app.kubernetes.io/name": context.name
              "app.kubernetes.io/component": "realtime-service"
              "app.kubernetes.io/managed-by": "kubevela"
              "app.kubernetes.io/part-of": "realtime-platform"
            }
            annotations: {
              "realtime-platform.oam.dev/bootstrap": "true"
              "realtime-platform.oam.dev/database": parameter.database
              "realtime-platform.oam.dev/visualization": parameter.visualization
              "realtime-platform.oam.dev/iot": "\\(parameter.iot)"
            }
          }
          spec: {
            template: {
              metadata: {
                annotations: {
                  "autoscaling.knative.dev/minScale": "1"
                  "autoscaling.knative.dev/maxScale": "10"
                  "run.googleapis.com/execution-environment": "gen2"
                }
                labels: {
                  "app.kubernetes.io/name": context.name
                  "app.kubernetes.io/version": parameter.version
                  "app.kubernetes.io/part-of": "realtime-platform"
                }
              }
              spec: {
                serviceAccountName: "knative-docker-sa"
                containers: [{
                  image: parameter.image
                  ports: [{
                    containerPort: parameter.port
                    name: "http1"
                  }]
                  resources: {
                    limits: {
                      cpu: parameter.resources.cpu
                      memory: parameter.resources.memory
                    }
                    requests: {
                      cpu: "250m"
                      memory: "512Mi"
                    }
                  }
                  env: [
                    {
                      name: "REALTIME_PLATFORM_NAME"
                      value: context.name
                    },
                    {
                      name: "AGENT_TYPE"
                      value: "realtime-data-processor"
                    },
                    {
                      name: "IMPLEMENTATION_TYPE"
                      value: "anthropic"
                    },
                    {
                      name: "LOG_LEVEL"
                      value: "INFO"
                    },
                    {
                      name: "WEBSOCKET_ENABLED"
                      value: "true"
                    }
                  ] + [
                    for k, v in parameter.environment {
                      name: k
                      value: v
                    }
                  ]
                  if parameter.envFrom != _|_ {
                    envFrom: parameter.envFrom
                  }
                  // Health checks for robust deployment
                  livenessProbe: {
                    httpGet: {
                      path: parameter.healthPath
                      port: parameter.port
                    }
                    initialDelaySeconds: 30
                    periodSeconds: 10
                  }
                  readinessProbe: {
                    httpGet: {
                      path: parameter.healthPath
                      port: parameter.port
                    }
                    initialDelaySeconds: 5
                    periodSeconds: 5
                  }
                }]
              }
            }
          }
        }
        
        // Secondary Outputs: Infrastructure + Repository Creation (equivalent to webservice)
        outputs: {
          // Infrastructure via RealtimePlatformClaim (always created)
          "realtime-infrastructure": {
            apiVersion: "platform.example.org/v1alpha1"
            kind: "RealtimePlatformClaim"
            metadata: {
              name: context.name + "-infrastructure"
              namespace: context.namespace
              labels: {
                "app.kubernetes.io/name": context.name
                "app.kubernetes.io/component": "realtime-infrastructure"
                "app.kubernetes.io/part-of": "realtime-platform"
              }
            }
            spec: {
              name: context.name
              appContainer: (*parameter.repository | context.name)
              database: parameter.database
              visualization: parameter.visualization
              iot: parameter.iot
              if parameter.dataRetention != _|_ {
                dataRetention: parameter.dataRetention
              }
              if parameter.mqttUsers != _|_ {
                mqttUsers: parameter.mqttUsers
              }
            }
          }
        }
        
        // Repository Creation Workflow (conditional - same pattern as webservice)
        if parameter.language != _|_ {
          outputs: {
            // Always include infrastructure
            "realtime-infrastructure": outputs["realtime-infrastructure"]
            
            // Add workflow trigger when language specified
            "workflow-trigger": {
              apiVersion: "batch/v1"
              kind: "Job"
              metadata: {
                name: context.name + "-workflow-trigger"
                namespace: context.namespace
                labels: {
                  "app.kubernetes.io/name": context.name
                  "app.kubernetes.io/component": "workflow-trigger"
                  "app.kubernetes.io/managed-by": "kubevela"
                  "app.kubernetes.io/part-of": "realtime-platform"
                }
                annotations: {
                  "realtime-platform.oam.dev/trigger-type": "argo-workflow"
                  "realtime-platform.oam.dev/workflow-template": "microservice-standard-contract"
                  "realtime-platform.oam.dev/source": "oam-driven"
                  "realtime-platform.oam.dev/platform-type": "realtime"
                }
              }
              spec: {
                template: {
                  spec: {
                    serviceAccountName: "argo-workflows-client"
                    restartPolicy: "Never"
                    volumes: [
                      {
                        name: "argo-token"
                        secret: {
                          secretName: "slack-api-argo-token-copy"
                        }
                      }
                    ]
                    containers: [{
                      name: "workflow-trigger"
                      image: "curlimages/curl:latest"
                      command: ["/bin/sh", "-c"]
                      volumeMounts: [
                        {
                          name: "argo-token"
                          mountPath: "/var/run/secrets/argo"
                          readOnly: true
                        }
                      ]
                      args: [
                        "echo '🚀 Triggering Argo Workflow for realtime platform: " + context.name + "'\n" +
                        "cat > /tmp/workflow.json << 'WORKFLOW_EOF'\n" +
                        "{\n" +
                        "  \"namespace\": \"argo\",\n" +
                        "  \"serverDryRun\": false,\n" +
                        "  \"workflow\": {\n" +
                        "    \"metadata\": {\n" +
                        "      \"generateName\": \"realtime-platform-creation-\",\n" +
                        "      \"namespace\": \"argo\",\n" +
                        "      \"labels\": {\n" +
                        "        \"created-by\": \"oam-componentdefinition\",\n" +
                        "        \"platform-name\": \"" + context.name + "\",\n" +
                        "        \"source\": \"oam-driven\",\n" +
                        "        \"platform-type\": \"realtime\"\n" +
                        "      }\n" +
                        "    },\n" +
                        "    \"spec\": {\n" +
                        "      \"workflowTemplateRef\": {\n" +
                        "        \"name\": \"microservice-standard-contract\"\n" +
                        "      },\n" +
                        "      \"arguments\": {\n" +
                        "        \"parameters\": [\n" +
                        "          {\"name\": \"resource-name\", \"value\": \"" + context.name + "\"},\n" +
                        "          {\"name\": \"resource-type\", \"value\": \"realtime-platform\"},\n" +
                        "          {\"name\": \"namespace\", \"value\": \"" + context.namespace + "\"},\n" +
                        "          {\"name\": \"user\", \"value\": \"oam-system\"},\n" +
                        "          {\"name\": \"description\", \"value\": \"OAM-driven realtime platform via ComponentDefinition\"},\n" +
                        "          {\"name\": \"github-org\", \"value\": \"shlapolosa\"},\n" +
                        "          {\"name\": \"docker-registry\", \"value\": \"docker.io/socrates12345\"},\n" +
                        "          {\"name\": \"slack-channel\", \"value\": \"#oam-notifications\"},\n" +
                        "          {\"name\": \"slack-user-id\", \"value\": \"OAM\"},\n" +
                        "          {\"name\": \"security-enabled\", \"value\": \"true\"},\n" +
                        "          {\"name\": \"observability-enabled\", \"value\": \"true\"},\n" +
                        "          {\"name\": \"backup-enabled\", \"value\": \"false\"},\n" +
                        "          {\"name\": \"environment-tier\", \"value\": \"development\"},\n" +
                        "          {\"name\": \"auto-create-dependencies\", \"value\": \"true\"},\n" +
                        "          {\"name\": \"resource-size\", \"value\": \"large\"},\n" +
                        "          {\"name\": \"microservice-language\", \"value\": \"" + parameter.language + "\"},\n" +
                        "          {\"name\": \"microservice-framework\", \"value\": \"" + (*"fastapi" | parameter.framework) + "\"},\n" +
                        "          {\"name\": \"microservice-database\", \"value\": \"" + parameter.database + "\"},\n" +
                        "          {\"name\": \"microservice-cache\", \"value\": \"redis\"},\n" +
                        "          {\"name\": \"microservice-expose-api\", \"value\": \"true\"},\n" +
                        "          {\"name\": \"realtime-websocket-enabled\", \"value\": \"true\"},\n" +
                        "          {\"name\": \"realtime-kafka-enabled\", \"value\": \"true\"},\n" +
                        "          {\"name\": \"realtime-mqtt-enabled\", \"value\": \"" + (*"true" | parameter.iot) + "\"},\n" +
                        "          {\"name\": \"target-vcluster\", \"value\": \"\"},\n" +
                        "          {\"name\": \"parent-appcontainer\", \"value\": \"\"},\n" +
                        "          {\"name\": \"repository-name\", \"value\": \"" + (*parameter.repository | context.name) + "\"}\n" +
                        "        ]\n" +
                        "      }\n" +
                        "    }\n" +
                        "  }\n" +
                        "}\n" +
                        "WORKFLOW_EOF\n" +
                        "echo '📋 Workflow JSON created, submitting to Argo...'\n" +
                        "cat /tmp/workflow.json\n" +
                        "RESPONSE=$(curl -s -k -w 'HTTPSTATUS:%{http_code}' -X POST -H \"Authorization: Bearer $(cat /var/run/secrets/argo/token)\" -H 'Content-Type: application/json' -H 'Accept: application/json' -d @/tmp/workflow.json https://argo-server.argo.svc.cluster.local:2746/api/v1/workflows/argo)\n" +
                        "HTTP_STATUS=$(echo $RESPONSE | tr -d '\\n' | sed -e 's/.*HTTPSTATUS://')\n" +
                        "BODY=$(echo $RESPONSE | sed -e 's/HTTPSTATUS:.*//g')\n" +
                        "echo '📊 HTTP Status:' $HTTP_STATUS\n" +
                        "echo '📄 Response:' $BODY\n" +
                        "if [ \"$HTTP_STATUS\" -eq 200 ] || [ \"$HTTP_STATUS\" -eq 201 ]; then\n" +
                        "  echo '✅ Workflow submission successful!'\n" +
                        "  echo \"$BODY\" | grep -o '\"name\":\"[^\"]*\"' | head -1\n" +
                        "else\n" +
                        "  echo '❌ Workflow submission failed with status:' $HTTP_STATUS\n" +
                        "  echo 'Response:' $BODY\n" +
                        "  exit 1\n" +
                        "fi"
                      ]
                    }]
                  }
                }
              }
            }
          }
        }
        
        parameter: {
          // Required (following webservice pattern)
          image: *"socrates12345/realtime-service-template:latest" | string
          
          // Service Configuration
          port: *8080 | int
          version: *"latest" | string
          healthPath: *"/health" | string
          
          // Resource Management
          resources: *{
            cpu: "1000m"
            memory: "2Gi"
          } | {
            cpu?: string
            memory?: string
          }
          
          // Environment Variables
          environment: *{} | {[string]: string}
          
          // Environment Variables from Secrets
          envFrom?: [...{
            secretRef: {
              name: string
            }
          }]
          
          // Optional Infrastructure Bootstrap (for repository creation equivalence)
          language?: string     // Triggers bootstrap: python, nodejs, java, go
          framework?: string    // fastapi, express, spring, gin
          repository?: string   // Git repository template name (defaults to name)
          
          // Realtime Platform Configuration
          database: *"postgres" | "postgres" | "mysql" | "mongodb"
          visualization: *"metabase" | "metabase" | "grafana"
          iot: *true | bool
          
          // Advanced optional
          dataRetention?: string // "7d", "30d", etc.
          mqttUsers?: [...{
            username: string
            password: string
          }]
        }