# ClusterGateway Template for vCluster Integration
# This template shows how to configure KubeVela to access vClusters
# Replace {{VCLUSTER_NAME}} and {{NAMESPACE}} with actual values

---
# Example ClusterGateway for a vCluster named "my-vcluster"
apiVersion: core.oam.dev/v1alpha1
kind: ClusterGateway
metadata:
  name: my-vcluster-gateway
  namespace: vela-system
  labels:
    app.kubernetes.io/name: vcluster-gateway
    app.kubernetes.io/part-of: kubevela-multicluster
    vcluster.io/cluster-name: my-vcluster
spec:
  clusterType: "vcluster"
  # vCluster endpoint - accessible from host cluster
  endpoint: "https://my-vcluster.default.svc.cluster.local:443"
  access:
    credential:
      type: "ServiceAccountToken"
      # This token will be created by the vCluster composition
      serviceAccountToken: "my-vcluster-kubevela-token"
    # Insecure for development - should use proper TLS in production
    insecure: true

---
# ConfigMap for dynamic ClusterGateway creation
# Used by vCluster composition to register new clusters
apiVersion: v1
kind: ConfigMap
metadata:
  name: vcluster-gateway-template
  namespace: vela-system
  labels:
    app.kubernetes.io/name: vcluster-gateway-template
    app.kubernetes.io/part-of: kubevela-multicluster
data:
  gateway-template.yaml: |
    apiVersion: core.oam.dev/v1alpha1
    kind: ClusterGateway
    metadata:
      name: "{{VCLUSTER_NAME}}-gateway"
      namespace: vela-system
      labels:
        app.kubernetes.io/name: vcluster-gateway
        app.kubernetes.io/part-of: kubevela-multicluster
        vcluster.io/cluster-name: "{{VCLUSTER_NAME}}"
    spec:
      clusterType: "vcluster"
      endpoint: "https://{{VCLUSTER_NAME}}.{{NAMESPACE}}.svc.cluster.local:443"
      access:
        credential:
          type: "ServiceAccountToken"
          serviceAccountToken: "{{VCLUSTER_NAME}}-kubevela-token"
        insecure: true