apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook
  namespace: argo
  labels:
    app: slack-notifications
    component: webhook-config
type: Opaque
stringData:
  # Replace with your actual Slack webhook URL
  webhook-url: "https://hooks.slack.com/services/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"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slack-notification-config
  namespace: argo
  labels:
    app: slack-notifications
    component: configuration
data:
  # Default notification settings
  default-emoji: "ℹ️"
  success-emoji: "✅"
  warning-emoji: "⚠️"
  error-emoji: "❌"
  
  # Workflow URL template for Argo Workflows
  # Replace with your actual Argo Workflows UI URL
  argo-workflows-base-url: "https://argo-workflows.example.com"
  
  # Slack channel settings (optional overrides)
  default-channel: "#general"
  vcluster-channel: "#infrastructure"
  appcontainer-channel: "#deployments"
  
  # Notification timing settings
  progress-interval: "300"  # Send progress updates every 5 minutes
  timeout-warning: "600"    # Warn if workflow runs longer than 10 minutes
  max-timeout: "1800"       # Maximum workflow timeout (30 minutes)