apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: standalone-appcontainer-interface
  namespace: argo
  annotations:
    description: "Standalone AppContainer interface using Parameter Mapping Layer - clean API for direct AppContainer usage"
spec:
  entrypoint: create-standalone-appcontainer
  arguments:
    parameters:
    - name: appcontainer-name
      value: "default-app"
    - name: namespace
      value: "default"
    - name: description
      value: "CLAUDE.md-compliant application container"
    - name: github-org
      value: "shlapolosa"
    - name: docker-registry
      value: "docker.io/socrates12345"
    - name: observability
      value: "true"
    - name: security
      value: "true"
    - name: vcluster-name
      value: ""
    - name: auto-create-vcluster
      value: "true"
    - name: user
      value: "unknown"
    - name: slack-channel
      value: "unknown"
    - name: slack-user-id
      value: "unknown"

  templates:
  - name: create-standalone-appcontainer
    steps:
    - - name: execute-standalone-appcontainer
        templateRef:
          name: appcontainer-mapping-layer
          template: create-standalone-appcontainer
        arguments:
          parameters:
          - name: appcontainer-name
            value: "{{workflow.parameters.appcontainer-name}}"
          - name: namespace
            value: "{{workflow.parameters.namespace}}"
          - name: description
            value: "{{workflow.parameters.description}}"
          - name: github-org
            value: "{{workflow.parameters.github-org}}"
          - name: docker-registry
            value: "{{workflow.parameters.docker-registry}}"
          - name: observability
            value: "{{workflow.parameters.observability}}"
          - name: security
            value: "{{workflow.parameters.security}}"
          - name: vcluster-name
            value: "{{workflow.parameters.vcluster-name}}"
          - name: auto-create-vcluster
            value: "{{workflow.parameters.auto-create-vcluster}}"
          - name: user
            value: "{{workflow.parameters.user}}"
          - name: slack-channel
            value: "{{workflow.parameters.slack-channel}}"
          - name: slack-user-id
            value: "{{workflow.parameters.slack-user-id}}"