apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slack-api-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shlapolosa/health-service-idp
    targetRevision: HEAD
    path: slack-api-server
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true