version: '3.8'

services:
  slack-api-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=development
      - PERSONAL_ACCESS_TOKEN=${PERSONAL_ACCESS_TOKEN:-your_github_token_here}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY:-shlapolosa/health-service-idp}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET:-your_slack_signing_secret}
    volumes:
      - ./src:/app/src
      - ./main.py:/app/main.py
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s