name: Debug AWS Authentication
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-2

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Debug GitHub Token Info
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Ref: ${{ github.ref }}"
        echo "SHA: ${{ github.sha }}"
        echo "Event name: ${{ github.event_name }}"
        echo "Workflow: ${{ github.workflow }}"
        echo "Job: ${{ github.job }}"
        
    - name: Try AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: Debug-${{ github.run_id }}
        role-duration-seconds: 3600
        
    - name: Test AWS Access
      run: |
        aws sts get-caller-identity
        echo "✅ AWS authentication successful"