name: Debug GitHub Secret Values
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Show Secret Values (First 20 chars only for security)
      run: |
        echo "AWS_ROLE_ARN starts with: $(echo '${{ secrets.AWS_ROLE_ARN }}' | cut -c1-20)..."
        echo "AWS_ROLE_ARN length: $(echo '${{ secrets.AWS_ROLE_ARN }}' | wc -c)"
        echo "Expected start: arn:aws:iam::263350"
        echo "Expected length: 55"
        
    - name: Test AWS Connection
      run: |
        echo "Testing AWS STS assume role..."
        echo "Role to assume: ${{ secrets.AWS_ROLE_ARN }}"
        
    - name: Try AWS Authentication
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-west-2
        role-session-name: Debug-${{ github.run_id }}
      continue-on-error: true
        
    - name: Test AWS Access (if auth succeeded)
      run: |
        aws sts get-caller-identity || echo "AWS authentication failed"